version: '3.3'

services:
  postgres12:
    image: postgres:12-alpine
    container_name: postgres12
    ports:
      - "5533:5433"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user
    # networks:
    #   - sonarNetwork
    volumes:
      - ./qpc-postgres:/var/lib/postgresql/data